### ISSUE TITLE
Restore model from config and weights for model training, via CLI option

### ISSUE THREAD

**Issue by nicolafan** [nicolafan/image-captioning-cnn-rnn#7]
Add a CLI option to model training that provides the possibility to continue training an existing model.

If the option is specified, with the model filename, we should ignore all the parameters that refer to the model architecture or raise an error if they are specified.

**Comment by IsraelAbebe** [comment]
@nicolafan 
want to work on this issue. Is the below command what you want to add as as option?

```
python -m src.models.train_model --model_path 'models/weights/train_20230314-012026.h5' --config_path models/config/train_20230314-012026.json
```

**Comment by nicolafan** [comment]
Hi @IsraelAbebe thank you for wanting to contribute!

Currently, according to the model evaluation which already restores a saved model, the command as I thought it would be:
```
python -m src.models.train_model --model_filename 'train_20230314'
```

And it will restore the weights and model accordingly.

I will assign this issue to you. Thanks!
